changelog:
  exclude:
    labels:
      - ignore-for-release
      - dependencies
    authors:
      - rapids-bot[bot]
      - dependabot[bot]
  categories:
    - title: "\U0001F6A8 Breaking Changes"
      labels:
        - breaking
    - title: "\U0001F41B Bug Fixes"
      labels:
        - bug
    - title: "\U0001F4D6 Documentation"
      labels:
        - doc
    - title: "\U0001F680 New Features"
      labels:
        - feature request
    - title: "\U0001F6E0\uFE0F Improvements"
      labels:
        - improvement
